export interface AwningPricingEntry {
    model: string;
    fabric: string;
    angle?: number;
    width_m: number;
    projection_m: number;
    price_eur: number;
}

export const AWNINGS_PRICING_TABLE: AwningPricingEntry[] = [
    { model: "BARCELONA", fabric: "Docril", width_m: 2.5, projection_m: 2.0, price_eur: 1523 },
    { model: "BARCELONA", fabric: "Docril", width_m: 3.0, projection_m: 2.0, price_eur: 1595 },
    { model: "BARCELONA", fabric: "Docril", width_m: 3.0, projection_m: 2.5, price_eur: 1695 },
    { model: "BARCELONA", fabric: "Docril", width_m: 3.5, projection_m: 2.0, price_eur: 1666 },
    { model: "BARCELONA", fabric: "Docril", width_m: 3.5, projection_m: 2.5, price_eur: 1768 },
    { model: "BARCELONA", fabric: "Docril", width_m: 3.5, projection_m: 3.0, price_eur: 1826 },
    { model: "BARCELONA", fabric: "Docril", width_m: 4.0, projection_m: 2.0, price_eur: 1791 },
    { model: "BARCELONA", fabric: "Docril", width_m: 4.0, projection_m: 2.5, price_eur: 1901 },
    { model: "BARCELONA", fabric: "Docril", width_m: 4.0, projection_m: 3.0, price_eur: 1969 },
    { model: "BARCELONA", fabric: "Docril", width_m: 4.5, projection_m: 2.0, price_eur: 1858 },
    { model: "BARCELONA", fabric: "Docril", width_m: 4.5, projection_m: 2.5, price_eur: 1969 },
    { model: "BARCELONA", fabric: "Docril", width_m: 4.5, projection_m: 3.0, price_eur: 2040 },
    { model: "BARCELONA", fabric: "Docril", width_m: 5.0, projection_m: 2.0, price_eur: 2113 },
    { model: "BARCELONA", fabric: "Docril", width_m: 5.0, projection_m: 2.5, price_eur: 2236 },
    { model: "BARCELONA", fabric: "Docril", width_m: 5.0, projection_m: 3.0, price_eur: 2317 },
    { model: "BARCELONA", fabric: "Docril", width_m: 5.5, projection_m: 2.0, price_eur: 2428 },
    { model: "BARCELONA", fabric: "Docril", width_m: 5.5, projection_m: 2.5, price_eur: 2548 },
    { model: "BARCELONA", fabric: "Docril", width_m: 5.5, projection_m: 3.0, price_eur: 2632 },
    { model: "BARCELONA", fabric: "Docril", width_m: 6.0, projection_m: 2.0, price_eur: 2897 },
    { model: "BARCELONA", fabric: "Docril", width_m: 6.0, projection_m: 2.5, price_eur: 3062 },
    { model: "BARCELONA", fabric: "Docril", width_m: 6.0, projection_m: 3.0, price_eur: 3169 },

    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 2.0, projection_m: 2.0, price_eur: 1049 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 2.0, projection_m: 2.5, price_eur: 1101 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 2.0, projection_m: 3.0, price_eur: 1174 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 2.5, projection_m: 2.0, price_eur: 1045 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 2.5, projection_m: 2.5, price_eur: 1225 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 2.5, projection_m: 3.0, price_eur: 1311 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 2.5, projection_m: 3.5, price_eur: 1409 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.0, projection_m: 2.0, price_eur: 1119 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.0, projection_m: 2.5, price_eur: 1188 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.0, projection_m: 3.0, price_eur: 1393 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.0, projection_m: 3.5, price_eur: 1511 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.0, projection_m: 4.0, price_eur: 1545 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.5, projection_m: 2.0, price_eur: 1171 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.5, projection_m: 2.5, price_eur: 1240 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.5, projection_m: 3.0, price_eur: 1331 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.5, projection_m: 3.5, price_eur: 1571 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 3.5, projection_m: 4.0, price_eur: 1610 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.0, projection_m: 2.0, price_eur: 1233 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.0, projection_m: 2.5, price_eur: 1313 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.0, projection_m: 3.0, price_eur: 1411 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.0, projection_m: 3.5, price_eur: 1588 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.0, projection_m: 4.0, price_eur: 1668 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.5, projection_m: 2.0, price_eur: 1323 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.5, projection_m: 2.5, price_eur: 1408 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.5, projection_m: 3.0, price_eur: 1514 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.5, projection_m: 3.5, price_eur: 1623 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 4.5, projection_m: 4.0, price_eur: 1705 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.0, projection_m: 2.0, price_eur: 1478 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.0, projection_m: 2.5, price_eur: 1576 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.0, projection_m: 3.0, price_eur: 1698 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.0, projection_m: 3.5, price_eur: 1856 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.0, projection_m: 4.0, price_eur: 1900 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.5, projection_m: 2.0, price_eur: 1510 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.5, projection_m: 2.5, price_eur: 1610 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.5, projection_m: 3.0, price_eur: 1731 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.5, projection_m: 3.5, price_eur: 1911 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 5.5, projection_m: 4.0, price_eur: 2010 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.0, projection_m: 2.0, price_eur: 1646 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.0, projection_m: 2.5, price_eur: 1763 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.0, projection_m: 3.0, price_eur: 1901 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.0, projection_m: 3.5, price_eur: 2013 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.0, projection_m: 4.0, price_eur: 2120 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.5, projection_m: 2.0, price_eur: 1796 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.5, projection_m: 2.5, price_eur: 1913 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.5, projection_m: 3.0, price_eur: 2048 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.5, projection_m: 3.5, price_eur: 2156 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 6.5, projection_m: 4.0, price_eur: 2226 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 7.0, projection_m: 2.0, price_eur: 2126 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 7.0, projection_m: 2.5, price_eur: 2261 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 7.0, projection_m: 3.0, price_eur: 2426 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 7.0, projection_m: 3.5, price_eur: 2549 },
    { model: "BLOOM_CLASSIC", fabric: "Docril", width_m: 7.0, projection_m: 4.0, price_eur: 2700 },

    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 2.0, projection_m: 2.0, price_eur: 1365 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 2.0, projection_m: 2.5, price_eur: 1431 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 2.0, projection_m: 3.0, price_eur: 1510 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 2.5, projection_m: 2.0, price_eur: 1410 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 2.5, projection_m: 2.5, price_eur: 1510 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 2.5, projection_m: 3.0, price_eur: 1625 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 2.5, projection_m: 3.5, price_eur: 1885 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.0, projection_m: 2.0, price_eur: 1513 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.0, projection_m: 2.5, price_eur: 1575 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.0, projection_m: 3.0, price_eur: 1690 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.0, projection_m: 3.5, price_eur: 1942 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.0, projection_m: 4.0, price_eur: 2035 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.5, projection_m: 2.0, price_eur: 1600 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.5, projection_m: 2.5, price_eur: 1663 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.5, projection_m: 3.0, price_eur: 1744 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.5, projection_m: 3.5, price_eur: 2005 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 3.5, projection_m: 4.0, price_eur: 2120 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.0, projection_m: 2.0, price_eur: 1779 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.0, projection_m: 2.5, price_eur: 1854 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.0, projection_m: 3.0, price_eur: 1944 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.0, projection_m: 3.5, price_eur: 2069 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.0, projection_m: 4.0, price_eur: 2195 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.5, projection_m: 2.0, price_eur: 1866 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.5, projection_m: 2.5, price_eur: 1941 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.5, projection_m: 3.0, price_eur: 2031 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.5, projection_m: 3.5, price_eur: 2154 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 4.5, projection_m: 4.0, price_eur: 2260 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.0, projection_m: 2.0, price_eur: 2004 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.0, projection_m: 2.5, price_eur: 2088 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.0, projection_m: 3.0, price_eur: 2191 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.0, projection_m: 3.5, price_eur: 2325 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.0, projection_m: 4.0, price_eur: 2441 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.5, projection_m: 2.0, price_eur: 2088 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.5, projection_m: 2.5, price_eur: 2175 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.5, projection_m: 3.0, price_eur: 2279 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.5, projection_m: 3.5, price_eur: 2429 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 5.5, projection_m: 4.0, price_eur: 2550 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 6.0, projection_m: 2.0, price_eur: 2235 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 6.0, projection_m: 2.5, price_eur: 2331 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 6.0, projection_m: 3.0, price_eur: 2444 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 6.0, projection_m: 3.5, price_eur: 2610 },
    { model: "BLOOM_CLASSIC_PLUS", fabric: "Docril", width_m: 6.0, projection_m: 4.0, price_eur: 2740 },

    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 2.0, projection_m: 1.5, price_eur: 504 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 2.5, projection_m: 1.5, price_eur: 510 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 2.5, projection_m: 2.0, price_eur: 572 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 3.0, projection_m: 1.5, price_eur: 590 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 3.0, projection_m: 2.0, price_eur: 670 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 3.0, projection_m: 2.5, price_eur: 735 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 3.5, projection_m: 1.5, price_eur: 597 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 3.5, projection_m: 2.0, price_eur: 673 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 3.5, projection_m: 2.5, price_eur: 737 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 3.5, projection_m: 3.0, price_eur: 819 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 4.0, projection_m: 1.5, price_eur: 667 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 4.0, projection_m: 2.0, price_eur: 761 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 4.0, projection_m: 2.5, price_eur: 840 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 4.0, projection_m: 3.0, price_eur: 932 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 4.5, projection_m: 1.5, price_eur: 694 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 4.5, projection_m: 2.0, price_eur: 783 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 4.5, projection_m: 2.5, price_eur: 862 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 4.5, projection_m: 3.0, price_eur: 959 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 5.0, projection_m: 1.5, price_eur: 762 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 5.0, projection_m: 2.0, price_eur: 861 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 5.0, projection_m: 2.5, price_eur: 953 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 5.0, projection_m: 3.0, price_eur: 1057 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 5.5, projection_m: 1.5, price_eur: 860 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 5.5, projection_m: 2.0, price_eur: 929 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 5.5, projection_m: 2.5, price_eur: 1021 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 5.5, projection_m: 3.0, price_eur: 1220 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 6.0, projection_m: 1.5, price_eur: 928 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 6.0, projection_m: 2.0, price_eur: 997 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 6.0, projection_m: 2.5, price_eur: 1100 },
    { model: "BLOOM_LIGHT", fabric: "Docril", width_m: 6.0, projection_m: 3.0, price_eur: 1300 },

    { model: "BLOOM_HARD", fabric: "Docril", width_m: 5.0, projection_m: 4.0, price_eur: 2925 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 5.0, projection_m: 4.5, price_eur: 3100 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 5.5, projection_m: 4.0, price_eur: 3015 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 5.5, projection_m: 4.5, price_eur: 3180 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 5.5, projection_m: 5.0, price_eur: 3230 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 6.0, projection_m: 4.0, price_eur: 3180 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 6.0, projection_m: 4.5, price_eur: 3280 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 6.0, projection_m: 5.0, price_eur: 3330 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 6.5, projection_m: 4.0, price_eur: 3339 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 6.5, projection_m: 4.5, price_eur: 3390 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 6.5, projection_m: 5.0, price_eur: 3440 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 7.0, projection_m: 4.0, price_eur: 3510 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 7.0, projection_m: 4.5, price_eur: 3530 },
    { model: "BLOOM_HARD", fabric: "Docril", width_m: 7.0, projection_m: 5.0, price_eur: 3580 },

    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.25, projection_m: 0.8, price_eur: 408 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.25, projection_m: 1.2, price_eur: 435 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.25, projection_m: 1.5, price_eur: 449 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.5, projection_m: 0.8, price_eur: 418 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.5, projection_m: 1.2, price_eur: 445 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.5, projection_m: 1.5, price_eur: 459 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.75, projection_m: 0.8, price_eur: 429 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.75, projection_m: 1.2, price_eur: 445 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 1.75, projection_m: 1.5, price_eur: 459 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.0, projection_m: 0.8, price_eur: 440 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.0, projection_m: 1.2, price_eur: 456 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.0, projection_m: 1.5, price_eur: 468 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.25, projection_m: 0.8, price_eur: 451 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.25, projection_m: 1.2, price_eur: 468 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.25, projection_m: 1.5, price_eur: 479 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.5, projection_m: 0.8, price_eur: 493 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.5, projection_m: 1.2, price_eur: 470 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.5, projection_m: 1.5, price_eur: 490 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.75, projection_m: 0.8, price_eur: 504 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.75, projection_m: 1.2, price_eur: 523 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 2.75, projection_m: 1.5, price_eur: 550 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.0, projection_m: 0.8, price_eur: 514 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.0, projection_m: 1.2, price_eur: 534 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.0, projection_m: 1.5, price_eur: 561 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.25, projection_m: 0.8, price_eur: 525 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.25, projection_m: 1.2, price_eur: 545 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.25, projection_m: 1.5, price_eur: 573 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.5, projection_m: 0.8, price_eur: 536 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.5, projection_m: 1.2, price_eur: 555 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.5, projection_m: 1.5, price_eur: 583 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.75, projection_m: 0.8, price_eur: 580 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.75, projection_m: 1.2, price_eur: 564 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 3.75, projection_m: 1.5, price_eur: 594 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.0, projection_m: 0.8, price_eur: 591 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.0, projection_m: 1.2, price_eur: 619 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.0, projection_m: 1.5, price_eur: 655 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.25, projection_m: 0.8, price_eur: 696 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.25, projection_m: 1.2, price_eur: 630 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.25, projection_m: 1.5, price_eur: 665 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.5, projection_m: 0.8, price_eur: 706 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.5, projection_m: 1.2, price_eur: 734 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 90, width_m: 4.5, projection_m: 1.5, price_eur: 773 },

    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.25, projection_m: 0.8, price_eur: 426 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.25, projection_m: 1.2, price_eur: 463 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.25, projection_m: 1.5, price_eur: 481 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.5, projection_m: 0.8, price_eur: 438 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.5, projection_m: 1.2, price_eur: 473 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.5, projection_m: 1.5, price_eur: 493 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.75, projection_m: 0.8, price_eur: 438 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.75, projection_m: 1.2, price_eur: 473 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 1.75, projection_m: 1.5, price_eur: 493 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.0, projection_m: 0.8, price_eur: 449 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.0, projection_m: 1.2, price_eur: 484 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.0, projection_m: 1.5, price_eur: 504 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.25, projection_m: 0.8, price_eur: 459 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.25, projection_m: 1.2, price_eur: 495 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.25, projection_m: 1.5, price_eur: 511 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.5, projection_m: 0.8, price_eur: 470 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.5, projection_m: 1.2, price_eur: 506 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.5, projection_m: 1.5, price_eur: 523 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.75, projection_m: 0.8, price_eur: 523 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.75, projection_m: 1.2, price_eur: 575 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 2.75, projection_m: 1.5, price_eur: 600 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.0, projection_m: 0.8, price_eur: 534 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.0, projection_m: 1.2, price_eur: 586 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.0, projection_m: 1.5, price_eur: 610 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.25, projection_m: 0.8, price_eur: 545 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.25, projection_m: 1.2, price_eur: 596 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.25, projection_m: 1.5, price_eur: 621 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.5, projection_m: 0.8, price_eur: 555 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.5, projection_m: 1.2, price_eur: 608 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.5, projection_m: 1.5, price_eur: 633 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.75, projection_m: 0.8, price_eur: 564 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.75, projection_m: 1.2, price_eur: 619 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 3.75, projection_m: 1.5, price_eur: 644 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.0, projection_m: 0.8, price_eur: 619 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.0, projection_m: 1.2, price_eur: 688 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.0, projection_m: 1.5, price_eur: 720 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.25, projection_m: 0.8, price_eur: 630 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.25, projection_m: 1.2, price_eur: 696 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.25, projection_m: 1.5, price_eur: 731 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.5, projection_m: 0.8, price_eur: 734 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.5, projection_m: 1.2, price_eur: 806 },
    { model: "BLOOM_WINDOW", fabric: "Docril", angle: 160, width_m: 4.5, projection_m: 1.5, price_eur: 839 },

    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 1.5, projection_m: 0.8, price_eur: 685 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 1.5, projection_m: 1.2, price_eur: 748 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 1.5, projection_m: 1.5, price_eur: 731 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 1.75, projection_m: 0.8, price_eur: 744 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 1.75, projection_m: 1.2, price_eur: 806 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 1.75, projection_m: 1.5, price_eur: 791 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.0, projection_m: 0.8, price_eur: 773 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.0, projection_m: 1.2, price_eur: 804 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.0, projection_m: 1.5, price_eur: 819 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.25, projection_m: 0.8, price_eur: 800 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.25, projection_m: 1.2, price_eur: 835 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.25, projection_m: 1.5, price_eur: 819 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.5, projection_m: 0.8, price_eur: 866 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.5, projection_m: 1.2, price_eur: 863 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.5, projection_m: 1.5, price_eur: 848 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.75, projection_m: 0.8, price_eur: 894 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.75, projection_m: 1.2, price_eur: 938 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 2.75, projection_m: 1.5, price_eur: 931 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.0, projection_m: 0.8, price_eur: 923 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.0, projection_m: 1.2, price_eur: 956 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.0, projection_m: 1.5, price_eur: 960 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.25, projection_m: 0.8, price_eur: 979 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.25, projection_m: 1.2, price_eur: 985 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.25, projection_m: 1.5, price_eur: 985 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.5, projection_m: 0.8, price_eur: 1006 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.5, projection_m: 1.2, price_eur: 1013 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.5, projection_m: 1.5, price_eur: 1044 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.75, projection_m: 0.8, price_eur: 1073 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.75, projection_m: 1.2, price_eur: 1073 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 3.75, projection_m: 1.5, price_eur: 1073 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 4.0, projection_m: 0.8, price_eur: 1100 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 4.0, projection_m: 1.2, price_eur: 1100 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 90, width_m: 4.0, projection_m: 1.5, price_eur: 1156 },

    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 1.5, projection_m: 0.8, price_eur: 706 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 1.5, projection_m: 1.2, price_eur: 775 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 1.5, projection_m: 1.5, price_eur: 769 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 1.75, projection_m: 0.8, price_eur: 766 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 1.75, projection_m: 1.2, price_eur: 804 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 1.75, projection_m: 1.5, price_eur: 829 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.0, projection_m: 0.8, price_eur: 794 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.0, projection_m: 1.2, price_eur: 835 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.0, projection_m: 1.5, price_eur: 856 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.25, projection_m: 0.8, price_eur: 794 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.25, projection_m: 1.2, price_eur: 831 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.25, projection_m: 1.5, price_eur: 856 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.5, projection_m: 0.8, price_eur: 823 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.5, projection_m: 1.2, price_eur: 910 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.5, projection_m: 1.5, price_eur: 885 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.75, projection_m: 0.8, price_eur: 898 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.75, projection_m: 1.2, price_eur: 938 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 2.75, projection_m: 1.5, price_eur: 988 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.0, projection_m: 0.8, price_eur: 925 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.0, projection_m: 1.2, price_eur: 956 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.0, projection_m: 1.5, price_eur: 1016 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.25, projection_m: 0.8, price_eur: 954 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.25, projection_m: 1.2, price_eur: 963 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.25, projection_m: 1.5, price_eur: 1044 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.5, projection_m: 0.8, price_eur: 1013 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.5, projection_m: 1.2, price_eur: 1023 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.5, projection_m: 1.5, price_eur: 1100 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.75, projection_m: 0.8, price_eur: 1041 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.75, projection_m: 1.2, price_eur: 1050 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 3.75, projection_m: 1.5, price_eur: 1129 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 4.0, projection_m: 0.8, price_eur: 1116 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 4.0, projection_m: 1.2, price_eur: 1129 },
    { model: "BLOOM_WINDOW_PLUS", fabric: "Docril", angle: 160, width_m: 4.0, projection_m: 1.5, price_eur: 1231 },

    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 1.5, projection_m: 1.5, price_eur: 439 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 1.5, projection_m: 2.0, price_eur: 495 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 1.5, projection_m: 2.5, price_eur: 548 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 1.5, projection_m: 3.0, price_eur: 602 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 1.5, projection_m: 3.5, price_eur: 655 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 1.5, projection_m: 4.0, price_eur: 708 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.0, projection_m: 1.5, price_eur: 479 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.0, projection_m: 2.0, price_eur: 530 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.0, projection_m: 2.5, price_eur: 586 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.0, projection_m: 3.0, price_eur: 639 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.0, projection_m: 3.5, price_eur: 694 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.0, projection_m: 4.0, price_eur: 746 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.5, projection_m: 1.5, price_eur: 566 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.5, projection_m: 2.0, price_eur: 633 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.5, projection_m: 2.5, price_eur: 698 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.5, projection_m: 3.0, price_eur: 766 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.5, projection_m: 3.5, price_eur: 831 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 2.5, projection_m: 4.0, price_eur: 898 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.0, projection_m: 1.5, price_eur: 603 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.0, projection_m: 2.0, price_eur: 671 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.0, projection_m: 2.5, price_eur: 738 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.0, projection_m: 3.0, price_eur: 803 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.0, projection_m: 3.5, price_eur: 871 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.0, projection_m: 4.0, price_eur: 936 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.5, projection_m: 1.5, price_eur: 643 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.5, projection_m: 2.0, price_eur: 708 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.5, projection_m: 2.5, price_eur: 776 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.5, projection_m: 3.0, price_eur: 841 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.5, projection_m: 3.5, price_eur: 908 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 3.5, projection_m: 4.0, price_eur: 973 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 4.0, projection_m: 1.5, price_eur: 730 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 4.0, projection_m: 2.0, price_eur: 809 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 4.0, projection_m: 2.5, price_eur: 888 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 4.0, projection_m: 3.0, price_eur: 966 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 4.0, projection_m: 3.5, price_eur: 1045 },
    { model: "BLOOM_ZIP", fabric: "Docril", width_m: 4.0, projection_m: 4.0, price_eur: 1124 }
];

export const EUR_TO_KGS = 100; // Placeholder, can be adjusted
